// <auto-generated />
// HINWEIS: Bewusst PROVIDER-NEUTRAL handgepflegt (s. 20260708072133_AddDataProtectionKeys.cs): der
// Migration-SQL-Generator liest bei `type: null` in Up() den Spaltentyp aus DIESEM TargetModel.
// Deshalb sind hier alle .HasColumnType(...) entfernt — jeder Provider wählt seinen Default.
// Bei einem künftigen `dotnet ef migrations add` analog neutralisieren.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Naudit.Infrastructure.Data;

#nullable disable

namespace Naudit.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NauditDbContext))]
    [Migration("20260708072133_AddDataProtectionKeys")]
    partial class AddDataProtectionKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FriendlyName");

                    b.Property<string>("Xml");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("DisplayName");

                    b.Property<string>("ExternalId");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Provider")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.GitHubLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Login")
                        .IsUnique();

                    b.ToTable("GitHubLinks");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<DateTime>("FirstReviewedAt");

                    b.Property<DateTime>("LastReviewedAt");

                    b.Property<string>("PlatformProjectId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PlatformProjectId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.ReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<long?>("InputTokens");

                    b.Property<string>("Model");

                    b.Property<long?>("OutputTokens");

                    b.Property<int>("PrNumber");

                    b.Property<int>("ProjectId");

                    b.Property<string>("Summary")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Verdict")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.ReviewFindingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Confidence")
                        .IsRequired();

                    b.Property<string>("File");

                    b.Property<int?>("Line");

                    b.Property<int>("ReviewId");

                    b.Property<string>("Severity")
                        .IsRequired();

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewFindings");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.GitHubLinkEntity", b =>
                {
                    b.HasOne("Naudit.Infrastructure.Data.AccountEntity", "Account")
                        .WithMany("GitHubLinks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.ReviewEntity", b =>
                {
                    b.HasOne("Naudit.Infrastructure.Data.ProjectEntity", "Project")
                        .WithMany("Reviews")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.ReviewFindingEntity", b =>
                {
                    b.HasOne("Naudit.Infrastructure.Data.ReviewEntity", "Review")
                        .WithMany("Findings")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.AccountEntity", b =>
                {
                    b.Navigation("GitHubLinks");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.ProjectEntity", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Naudit.Infrastructure.Data.ReviewEntity", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
