<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Naudit.Benchmark</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Naudit.Core\Naudit.Core.csproj" />
    <ProjectReference Include="..\..\src\Naudit.Infrastructure\Naudit.Infrastructure.csproj" />
  </ItemGroup>

</Project>
