{{- if not .Values.bootstrap.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "naudit.fullname" . }}-bootstrap
  labels:
    {{- include "naudit.labels" . | nindent 4 }}
stringData:
  admin-initial-password: {{ required "admin.initialPassword setzen (oder bootstrap.existingSecret verwenden)" .Values.admin.initialPassword | quote }}
  {{- if eq .Values.db.provider "Postgres" }}
  db-connection-string: {{ required "db.connectionString setzen (oder bootstrap.existingSecret verwenden)" .Values.db.connectionString | quote }}
  {{- end }}
{{- end }}
